name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  build:
    name: Run tests on ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        experimental:
          - false
        include:
          - os: windows-latest
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Node.js environment
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests
        run: npm test
        if: runner.os != 'Linux'
