name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  build:
    name: Run tests on ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        experimental:
          - false
        include:
          - os: windows-latest
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the source code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Set up Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests
        run: npm test
        if: runner.os != 'Linux'
