name: Publish

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  publish:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Node.js environment
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
